### ISSUE TITLE
Change commands.json format

### ISSUE THREAD

**Issue by Arcyvilk** [viktor-mains/ViktorBot#13]
Commit aae3173 introduced new object-based system of generating commands. it uses the format below:

```ts
export type ICommand = {
    keyword: string,
    description?: string,
    isProtected?: boolean,
    isDisabled?: boolean,
    isModOnly?: boolean,        
    refusal?: string
}
```

<details>
    <summary>Old version (click to expand)</summary>

---

Proposed new format:
```js
{
    "keyword": "string",
    "response": {
        "type": "text | embed | function",
        "content": "string | function()",
        "title?": "string", // when response.type is 'embed'
        "arguments?": [ "string" ], // when response.type is 'function'
    },
    "description?": "string", // if not provided, doesn't show in command list
    "isProtected?": "boolean", // default: true
    "isAvailable": "boolean", // default: true
    "isModCommand": "boolean", // default: false
     "refusal": "string" // text appearing when bot refuses to answer
}
```
</details>

**Comment by Arcyvilk** [comment]
`responseType` is relevant because most of the commands are simple texts returned as a reply, so their content can be kept as a string in `response` field. If the command is more complicated, then `responseType` is marked as `function` and `response` points to the function that needs to be executed.

There's probably a better way to handle it but this one currently is the most intuitive one I've managed to think of

**Comment by Aergwyn** [comment]
Which still leaves the question why it returns anything at all.

**Comment by Arcyvilk** [comment]
I don't understand, do you mean that every command should invoke an external function with its own logic?

**Comment by Aergwyn** [comment]
Every command should be responsible for it's own logic. That includes whatever it sends to whoever. That's why I wouldn't expect a command to return anything.
I may be misunderstanding how JS works here though.

**Comment by Arcyvilk** [comment]
I'm too lightheaded today to understand if we're thinking of the same thing. In the commit 757ce27 I introduced how I imagine this logic to work

**Comment by Arcyvilk** [comment]
@Aergwyn I made a thing

**Comment by Arcyvilk** [comment]
This has been changed in Vikbot 3.0 where all the JSON data files got migrated to database.
