### ISSUE TITLE
!topmembers change/extension

### ISSUE THREAD

**Issue by Aergwyn** [viktor-mains/ViktorBot#20]
Currently the command (!topmembers) displays the top 19 members of the server by message count.
Apparently this already hides members not on the server so I'll skip past that.

I'd prefer it to only show the top 10 as it seems a more sane number.
Additionally it could be renamed to something more simple (!activity) which could then be extended with a specific user (!activity \<user\>) to get a response akin to
>\<user\> ranks 46 out of 999 with \<amount\> messages.

This would allow people beyond 19 (or in the shorter version, 10) to figure out where they stand.

**Comment by Arcyvilk** [comment]
This is actually added now with the `!profile` command!
